/* eslint-disable n8n-nodes-base/node-param-options-type-unsorted-items */
import type { INodeProperties } from 'n8n-workflow';

export const dataExtractionNanoGPTParameterProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['dataExtraction'] } },
		options: [
			{ name: 'Web Scrape', value: 'firecrawl', description: 'Scrape, map, or crawl web pages', action: 'Web scrape' },
			{ name: 'Google Maps Search', value: 'googleMaps', description: 'Search Google Maps for places', action: 'Google maps search' },
			{ name: 'Google Maps Reviews', value: 'googleMapsReviews', description: 'Extract Google Maps reviews', action: 'Google maps reviews' },
			{ name: 'Facebook Ads', value: 'facebookAds', description: 'Extract Facebook/Meta ad library data', action: 'Facebook ads' },
			{ name: 'Instagram Profile', value: 'instagramProfile', description: 'Extract Instagram profile data', action: 'Instagram profile' },
			{ name: 'Instagram Posts', value: 'instagramPosts', description: 'Extract Instagram posts', action: 'Instagram posts' },
			{ name: 'Instagram Reels', value: 'instagramReels', description: 'Extract Instagram Reels', action: 'Instagram reels' },
			{ name: 'Reddit Extract', value: 'reddit', description: 'Extract Reddit posts, comments, users', action: 'Reddit extract' },
			{ name: 'TikTok Extract', value: 'tiktok', description: 'Extract TikTok content', action: 'Tiktok extract' },
			{ name: 'LinkedIn Profile', value: 'linkedinProfile', description: 'Enrich LinkedIn profile data', action: 'Linkedin profile' },
			{ name: 'Hunter', value: 'hunter', description: 'Email/domain intelligence (domain-search, email-finder, etc.)', action: 'Hunter' },
		],
		default: 'firecrawl',
	},

	// ── Common ──
	{
		displayName: 'Max Total Charge (USD)',
		name: 'maxTotalChargeUsd',
		type: 'number',
		displayOptions: { show: { resource: ['dataExtraction'] } },
		default: 0,
		description: 'Maximum USD to spend on this extraction. Required for unbounded searches.',
	},

	// ═══════════════════════════════════════════════
	// FIRECRAWL
	// ═══════════════════════════════════════════════
	{
		displayName: 'URL',
		name: 'firecrawlUrl',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['firecrawl'] } },
		default: '',
		description: 'Target URL to scrape, map, or crawl',
	},
	{
		displayName: 'Operation',
		name: 'firecrawlOperation',
		type: 'options',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['firecrawl'] } },
		options: [
			{ name: 'Scrape', value: 'scrape' },
			{ name: 'Map', value: 'map' },
			{ name: 'Crawl', value: 'crawl' },
		],
		default: 'scrape',
	},
	{
		displayName: 'Firecrawl Options',
		name: 'firecrawlOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['firecrawl'] } },
		options: [
			{
				displayName: 'Formats',
				name: 'formats',
				type: 'string',
				default: '',
				placeholder: 'markdown, html',
				description: 'Comma-separated output formats: markdown, html, rawHtml, screenshot, links',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Max Returned Pages',
				name: 'maxReturnedPages',
				type: 'number',
				default: 0,
				description: 'Maximum number of pages returned for crawl operation',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Search term for map operation',
			},
			{
				displayName: 'Wait For Finish (Seconds)',
				name: 'waitForFinishSecs',
				type: 'number',
				default: 0,
				description: 'How long to wait for the operation to finish, capped at 240 seconds',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// GOOGLE MAPS
	// ═══════════════════════════════════════════════
	{
		displayName: 'Search Strings',
		name: 'googleMapsSearchStrings',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMaps'] } },
		default: '',
		placeholder: 'coffee shops in Amsterdam, restaurants in Paris',
		description: 'Comma-separated search queries. At least one input (search strings, URLs, or place IDs) required.',
	},
	{
		displayName: 'Start URLs',
		name: 'googleMapsStartUrls',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMaps'] } },
		default: '',
		placeholder: 'https://www.google.com/maps/place/..., ...',
		description: 'Comma-separated Google Maps place URLs',
	},
	{
		displayName: 'Place IDs',
		name: 'googleMapsPlaceIds',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMaps'] } },
		default: '',
		placeholder: 'ChIJ..., ChIJ...',
		description: 'Comma-separated Google Maps place IDs',
	},
	{
		displayName: 'Google Maps Options',
		name: 'googleMapsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMaps'] } },
		options: [
			{
				displayName: 'Max Crawled Places Per Search',
				name: 'maxCrawledPlacesPerSearch',
				type: 'number',
				default: 0,
				description: 'Maximum places to crawl per search query',
			},
			{
				displayName: 'Max Images',
				name: 'maxImages',
				type: 'number',
				default: 0,
				description: 'Maximum number of images to extract per place',
			},
			{
				displayName: 'Max Reviews',
				name: 'googleMapsMaxReviews',
				type: 'number',
				default: 0,
				description: 'Maximum number of reviews to extract per place',
			},
			{
				displayName: 'Result Limit',
				name: 'googleMapsResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Scrape Contacts',
				name: 'scrapeContacts',
				type: 'boolean',
				default: false,
				description: 'Whether to extract contact information from place detail pages',
			},
			{
				displayName: 'Scrape Place Detail Page',
				name: 'scrapePlaceDetailPage',
				type: 'boolean',
				default: false,
				description: 'Whether to scrape full place detail pages for each result',
			},
			{
				displayName: 'Scrape Social Media Profiles',
				name: 'scrapeSocialMediaProfiles',
				type: 'boolean',
				default: false,
				description: 'Whether to extract social media profile links',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// GOOGLE MAPS REVIEWS
	// ═══════════════════════════════════════════════
	{
		displayName: 'Start URLs',
		name: 'googleMapsReviewsStartUrls',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMapsReviews'] } },
		default: '',
		placeholder: 'https://www.google.com/maps/place/..., ...',
		description: 'Comma-separated Google Maps place URLs. At least one input (URLs or place IDs) required.',
	},
	{
		displayName: 'Place IDs',
		name: 'googleMapsReviewsPlaceIds',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMapsReviews'] } },
		default: '',
		placeholder: 'ChIJ..., ChIJ...',
		description: 'Comma-separated Google Maps place IDs',
	},
	{
		displayName: 'Google Maps Reviews Options',
		name: 'googleMapsReviewsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['googleMapsReviews'] } },
		options: [
			{
				displayName: 'Language',
				name: 'language',
				type: 'string',
				default: 'en',
				description: 'Language code for reviews (e.g. en, fr, de)',
			},
			{
				displayName: 'Max Reviews',
				name: 'googleMapsReviewsMaxReviews',
				type: 'number',
				default: 10,
				description: 'Maximum number of reviews to extract',
			},
			{
				displayName: 'Personal Data',
				name: 'personalData',
				type: 'boolean',
				default: true,
				description: 'Whether to include reviewer personal data',
			},
			{
				displayName: 'Result Limit',
				name: 'googleMapsReviewsResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 1000,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Reviews Origin',
				name: 'reviewsOrigin',
				type: 'options',
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Google', value: 'google' },
					{ name: 'Scraped', value: 'scraped' },
				],
				default: 'all',
				description: 'Origin filter for reviews',
			},
			{
				displayName: 'Reviews Sort',
				name: 'reviewsSort',
				type: 'options',
				options: [
					{ name: 'Newest', value: 'newest' },
					{ name: 'Most Relevant', value: 'mostRelevant' },
					{ name: 'Highest Rating', value: 'highestRating' },
					{ name: 'Lowest Rating', value: 'lowestRating' },
				],
				default: 'newest',
				description: 'How to sort reviews',
			},
			{
				displayName: 'Reviews Start Date',
				name: 'reviewsStartDate',
				type: 'string',
				default: '',
				placeholder: 'YYYY-MM-DD',
				description: 'Only include reviews posted on or after this date. Use with newest sort.',
			},
			{
				displayName: 'Wait For Finish (Seconds)',
				name: 'waitForFinishSecs',
				type: 'number',
				default: 240,
				description: 'How long to wait for the operation to finish, capped at 240 seconds',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// FACEBOOK ADS
	// ═══════════════════════════════════════════════
	{
		displayName: 'Start URLs',
		name: 'facebookAdsStartUrls',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['facebookAds'] } },
		default: '',
		placeholder: 'https://www.facebook.com/ads/library/..., ...',
		description: 'Comma-separated Facebook Page or Meta Ad Library URLs',
	},
	{
		displayName: 'Facebook Ads Options',
		name: 'facebookAdsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['facebookAds'] } },
		options: [
			{
				displayName: 'Active Status',
				name: 'activeStatus',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
				description: 'Filter by ad active status',
			},
			{
				displayName: 'Result Limit',
				name: 'facebookAdsResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Results Limit',
				name: 'facebookAdsResultsLimit',
				type: 'number',
				default: 0,
				description: 'Maximum number of ad results to return',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// INSTAGRAM PROFILE
	// ═══════════════════════════════════════════════
	{
		displayName: 'Usernames',
		name: 'instagramProfileUsernames',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramProfile'] } },
		default: '',
		placeholder: 'nike, adidas, zara',
		description: 'Comma-separated Instagram usernames, profile URLs, or profile IDs',
	},
	{
		displayName: 'Instagram Profile Options',
		name: 'instagramProfileOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramProfile'] } },
		options: [
			{
				displayName: 'Include About Section',
				name: 'includeAboutSection',
				type: 'boolean',
				default: false,
				description: 'Whether to include the profile about/bio section',
			},
			{
				displayName: 'Result Limit',
				name: 'instagramProfileResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// INSTAGRAM POSTS
	// ═══════════════════════════════════════════════
	{
		displayName: 'Usernames',
		name: 'instagramPostsUsernames',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramPosts'] } },
		default: '',
		placeholder: 'nike, adidas',
		description: 'Comma-separated Instagram usernames, profile URLs, or post URLs',
	},
	{
		displayName: 'Instagram Posts Options',
		name: 'instagramPostsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramPosts'] } },
		options: [
			{
				displayName: 'Data Detail Level',
				name: 'dataDetailLevel',
				type: 'options',
				options: [
					{ name: 'Basic Data', value: 'basicData' },
					{ name: 'Detailed Data', value: 'detailedData' },
				],
				default: 'detailedData',
				description: 'Level of detail for extracted data',
			},
			{
				displayName: 'Result Limit',
				name: 'instagramPostsResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 20,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Results Limit',
				name: 'instagramPostsResultsLimit',
				type: 'number',
				default: 10,
				description: 'Maximum number of post results to return',
			},
			{
				displayName: 'Skip Pinned Posts',
				name: 'skipPinnedPosts',
				type: 'boolean',
				default: false,
				description: 'Whether to skip pinned posts in the results',
			},
			{
				displayName: 'Wait For Finish (Seconds)',
				name: 'waitForFinishSecs',
				type: 'number',
				default: 180,
				description: 'How long to wait for the operation to finish',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// INSTAGRAM REELS
	// ═══════════════════════════════════════════════
	{
		displayName: 'Usernames',
		name: 'instagramReelsUsernames',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramReels'] } },
		default: '',
		placeholder: 'nike, adidas',
		description: 'Comma-separated Instagram usernames, profile URLs, or post URLs',
	},
	{
		displayName: 'Instagram Reels Options',
		name: 'instagramReelsOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['instagramReels'] } },
		options: [
			{
				displayName: 'Result Limit',
				name: 'instagramReelsResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Results Limit',
				name: 'instagramReelsResultsLimit',
				type: 'number',
				default: 0,
				description: 'Maximum number of reel results to return',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// REDDIT
	// ═══════════════════════════════════════════════
	{
		displayName: 'Start URLs',
		name: 'redditStartUrls',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['reddit'] } },
		default: '',
		placeholder: 'https://reddit.com/r/sub/comments/abc/title, https://redd.it/abc',
		description: 'Comma-separated Reddit POST URLs. For browsing subreddits, use Searches instead. At least one input (URLs or searches) required.',
	},
	{
		displayName: 'Searches',
		name: 'redditSearches',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['reddit'] } },
		default: '',
		placeholder: 'term1, term2',
		description: 'Comma-separated search terms',
	},
	{
		displayName: 'Reddit Options',
		name: 'redditOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['reddit'] } },
		options: [
			{
				displayName: 'Include NSFW',
				name: 'includeNSFW',
				type: 'boolean',
				default: true,
				description: 'Whether to include NSFW content in results',
			},
			{
				displayName: 'Max Comments',
				name: 'maxComments',
				type: 'number',
				default: 10,
				description: 'Maximum number of comments to extract',
			},
			{
				displayName: 'Max Communities',
				name: 'maxCommunities',
				type: 'number',
				default: 0,
				description: 'Maximum number of communities to extract',
			},
			{
				displayName: 'Max Items',
				name: 'maxItems',
				type: 'number',
				default: 10,
				description: 'Maximum total items to return across all types',
			},
			{
				displayName: 'Max Post Count',
				name: 'maxPostCount',
				type: 'number',
				default: 10,
				description: 'Maximum number of posts to extract',
			},
			{
				displayName: 'Max Users',
				name: 'maxUsers',
				type: 'number',
				default: 0,
				description: 'Maximum number of users to extract',
			},
			{
				displayName: 'Result Limit',
				name: 'redditResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 10,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Search Comments',
				name: 'searchComments',
				type: 'boolean',
				default: false,
				description: 'Whether to search and extract comments',
			},
			{
				displayName: 'Search Communities',
				name: 'searchCommunities',
				type: 'boolean',
				default: false,
				description: 'Whether to search and extract communities',
			},
			{
				displayName: 'Search Posts',
				name: 'searchPosts',
				type: 'boolean',
				default: true,
				description: 'Whether to search and extract posts',
			},
			{
				displayName: 'Search Users',
				name: 'searchUsers',
				type: 'boolean',
				default: false,
				description: 'Whether to search and extract users',
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				options: [
					{ name: 'New', value: 'new' },
					{ name: 'Hot', value: 'hot' },
					{ name: 'Top', value: 'top' },
					{ name: 'Rising', value: 'rising' },
				],
				default: 'new',
				description: 'How to sort Reddit results',
			},
			{
				displayName: 'Wait For Finish (Seconds)',
				name: 'waitForFinishSecs',
				type: 'number',
				default: 180,
				description: 'How long to wait for the operation to finish, capped at 240 seconds',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// TIKTOK
	// ═══════════════════════════════════════════════
	{
		displayName: 'Hashtags',
		name: 'tiktokHashtags',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['tiktok'] } },
		default: '',
		placeholder: 'fyp, viral, trending',
		description: 'Comma-separated TikTok hashtags. At least one input (hashtags, profiles, queries, or post URLs) required.',
	},
	{
		displayName: 'Profiles',
		name: 'tiktokProfiles',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['tiktok'] } },
		default: '',
		placeholder: '@username1, @username2',
		description: 'Comma-separated TikTok profile usernames or URLs',
	},
	{
		displayName: 'Search Queries',
		name: 'tiktokSearchQueries',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['tiktok'] } },
		default: '',
		placeholder: 'query1, query2',
		description: 'Comma-separated search queries',
	},
	{
		displayName: 'Post URLs',
		name: 'tiktokPostURLs',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['tiktok'] } },
		default: '',
		placeholder: 'https://www.tiktok.com/@user/video/..., ...',
		description: 'Comma-separated TikTok post URLs',
	},
	{
		displayName: 'TikTok Options',
		name: 'tiktokOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['tiktok'] } },
		options: [
			{
				displayName: 'Max Profiles Per Query',
				name: 'maxProfilesPerQuery',
				type: 'number',
				default: 5,
				description: 'Maximum profiles to return per search query',
			},
			{
				displayName: 'Result Limit',
				name: 'tiktokResultLimit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 10,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Results Per Page',
				name: 'resultsPerPage',
				type: 'number',
				default: 10,
				description: 'Number of results per page',
			},
			{
				displayName: 'Search Section',
				name: 'searchSection',
				type: 'string',
				default: '',
				description: 'Section to search within (e.g. top, video, user)',
			},
		],
	},

	// ═══════════════════════════════════════════════
	// LINKEDIN PROFILE
	// ═══════════════════════════════════════════════
	{
		displayName: 'Profile URLs',
		name: 'linkedinProfileUrls',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['linkedinProfile'] } },
		default: '',
		placeholder: 'https://www.linkedin.com/in/username, ...',
		description: 'Comma-separated LinkedIn profile URLs to enrich',
	},

	// ═══════════════════════════════════════════════
	// HUNTER
	// ═══════════════════════════════════════════════
	{
		displayName: 'Endpoint',
		name: 'hunterEndpoint',
		type: 'options',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'] } },
		options: [
			{ name: 'Combined Enrichment', value: 'combined/find' },
			{ name: 'Company Enrichment', value: 'companies/find' },
			{ name: 'Discover Companies', value: 'discover' },
			{ name: 'Domain Search', value: 'domain-search' },
			{ name: 'Email Count', value: 'email-count' },
			{ name: 'Email Enrichment', value: 'people/find' },
			{ name: 'Email Finder', value: 'email-finder' },
			{ name: 'Email Verifier', value: 'email-verifier' },
		],
		default: 'domain-search',
		description: 'Hunter endpoint to call',
	},
	{
		displayName: 'Hunter Options',
		name: 'hunterOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'] } },
		options: [
			{
				displayName: 'Additional Parameters (JSON)',
				name: 'params',
				type: 'json',
				default: '{}',
				description: 'Additional query parameters (GET) or JSON body fields (POST) forwarded to Hunter',
			},
		],
	},

	// ── Domain Search ──
	{
		displayName: 'Domain',
		name: 'hunterDomain',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search'] } },
		default: '',
		description: 'Domain name to search for email addresses',
	},
	{
		displayName: 'Company',
		name: 'hunterCompany',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search'] } },
		default: '',
		description: 'Company name for the domain search',
	},
	{
		displayName: 'Email Type',
		name: 'hunterEmailType',
		type: 'options',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: 'Personal', value: 'personal' },
			{ name: 'Generic', value: 'generic' },
		],
		default: '',
		description: 'Filter by email type',
	},
	{
		displayName: 'Department',
		name: 'hunterDepartment',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search'] } },
		default: '',
		description: 'Filter by department (e.g. marketing, engineering)',
	},
	{
		displayName: 'Seniority',
		name: 'hunterSeniority',
		type: 'options',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: 'Junior', value: 'junior' },
			{ name: 'Senior', value: 'senior' },
			{ name: 'Executive', value: 'executive' },
		],
		default: '',
		description: 'Filter by seniority level',
	},
	{
		displayName: 'Limit',
		name: 'hunterLimit',
		type: 'number',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search', 'discover', 'email-finder', 'email-count'] } },
		default: 10,
		description: 'Maximum number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'hunterOffset',
		type: 'number',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['domain-search', 'discover'] } },
		default: 0,
		description: 'Number of results to skip',
	},

	// ── Email Finder ──
	{
		displayName: 'Domain',
		name: 'hunterFinderDomain',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: '',
		description: 'Domain name to find an email for',
	},
	{
		displayName: 'Company',
		name: 'hunterFinderCompany',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: '',
		description: 'Company name for the email search',
	},
	{
		displayName: 'LinkedIn Handle',
		name: 'hunterFinderLinkedin',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder', 'people/find'] } },
		default: '',
		description: 'LinkedIn profile handle or URL for the person',
	},
	{
		displayName: 'Full Name',
		name: 'hunterFullName',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: '',
		description: 'Full name of the person',
	},
	{
		displayName: 'First Name',
		name: 'hunterFirstName',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: '',
		description: 'First name of the person',
	},
	{
		displayName: 'Last Name',
		name: 'hunterLastName',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: '',
		description: 'Last name of the person',
	},
	{
		displayName: 'Max Duration',
		name: 'hunterMaxDuration',
		type: 'number',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-finder'] } },
		default: 0,
		description: 'Maximum search duration in seconds',
	},

	// ── Email Verifier ──
	{
		displayName: 'Email',
		name: 'hunterEmail',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-verifier'] } },
		default: '',
		description: 'Email address to verify',
	},

	// ── Email Count ──
	{
		displayName: 'Domain',
		name: 'hunterCountDomain',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-count'] } },
		default: '',
		description: 'Domain name to count emails for',
	},
	{
		displayName: 'Company',
		name: 'hunterCountCompany',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-count'] } },
		default: '',
		description: 'Company name for email counting',
	},
	{
		displayName: 'Email Type',
		name: 'hunterCountEmailType',
		type: 'options',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['email-count'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: 'Personal', value: 'personal' },
			{ name: 'Generic', value: 'generic' },
		],
		default: '',
		description: 'Filter by email type',
	},

	// ── Email Enrichment ──
	{
		displayName: 'Email',
		name: 'hunterEnrichEmail',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['people/find'] } },
		default: '',
		description: 'Email address to enrich',
	},

	// ── Company Enrichment ──
	{
		displayName: 'Domain',
		name: 'hunterCompanyEnrichDomain',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['companies/find'] } },
		default: '',
		description: 'Domain name for company enrichment',
	},
	{
		displayName: 'Clearbit Format',
		name: 'hunterCompanyClearbit',
		type: 'boolean',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['companies/find', 'combined/find'] } },
		default: false,
		description: 'Whether to return data in Clearbit-compatible format',
	},

	// ── Combined Enrichment ──
	{
		displayName: 'Email',
		name: 'hunterCombinedEmail',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['combined/find'] } },
		default: '',
		description: 'Email address for combined enrichment',
	},

	// ── Discover ──
	{
		displayName: 'Query',
		name: 'hunterDiscoverQuery',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		default: '',
		description: 'Search query to discover leads',
	},
	{
		displayName: 'Domain',
		name: 'hunterDiscoverDomain',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		default: '',
		description: 'Domain name to discover leads for',
	},
	{
		displayName: 'Company',
		name: 'hunterDiscoverCompany',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		default: '',
		description: 'Company name to discover leads for',
	},
	{
		displayName: 'Industries',
		name: 'hunterDiscoverIndustries',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		default: '',
		description: 'Comma-separated industry filters',
	},
	{
		displayName: 'Country',
		name: 'hunterDiscoverCountry',
		type: 'string',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		default: '',
		description: 'Country code to filter by (e.g. US, FR, DE)',
	},
	{
		displayName: 'Headcount',
		name: 'hunterDiscoverHeadcount',
		type: 'options',
		displayOptions: { show: { resource: ['dataExtraction'], operation: ['hunter'], hunterEndpoint: ['discover'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: '1-10', value: '1-10' },
			{ name: '11-50', value: '11-50' },
			{ name: '51-200', value: '51-200' },
			{ name: '201-500', value: '201-500' },
			{ name: '501-1000', value: '501-1000' },
			{ name: '1001-5000', value: '1001-5000' },
			{ name: '5001-10000', value: '5001-10000' },
			{ name: '10001+', value: '10001+' },
		],
		default: '',
		description: 'Filter by company headcount range',
	},
];
