/* eslint-disable n8n-nodes-base/node-param-collection-type-unsorted-items, n8n-nodes-base/node-param-options-type-unsorted-items, n8n-nodes-base/node-param-description-boolean-without-whether */
import type { INodeProperties } from 'n8n-workflow';

export const imageNanoGPTParameterProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['imageGeneration'],
			},
		},
		options: [
			{
				name: 'Generate Image',
				value: 'generateImage',
				description: 'Generate images from text prompts',
				action: 'Generate image',
			},
		],
		default: 'generateImage',
	},

	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				operation: ['generateImage'],
			},
		},
		default: '',
		placeholder: 'A beautiful sunset over mountains',
		description: 'Text description of the image to generate',
	},

	{
		displayName: 'Model Name or ID',
		name: 'imageModel',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getImageModels',
		},
		displayOptions: {
			show: {
				operation: ['generateImage'],
			},
		},
		default: 'nano-banana-pro',
		description: 'Image generation model to use. Models are dynamically loaded from the API. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},

	{
		displayName: 'Advanced Options',
		name: 'imageAdvancedOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				operation: ['generateImage'],
			},
		},
		options: [
			{
				displayName: 'Size',
				name: 'size',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: '256x256', value: '256x256' },
					{ name: '512x512', value: '512x512' },
					{ name: '768x768', value: '768x768' },
					{ name: '768x1024 (Portrait 3:4)', value: '768x1024' },
					{ name: '1024x768 (Landscape 4:3)', value: '1024x768' },
					{ name: '576x1024 (Portrait 9:16)', value: '576x1024' },
					{ name: '1024x576 (Landscape 16:9)', value: '1024x576' },
					{ name: '1024x1024', value: '1024x1024' },
					{ name: '1024x1536 (Portrait 2:3)', value: '1024x1536' },
					{ name: '1536x1024 (Landscape 3:2)', value: '1536x1024' },
					{ name: '1024x1792 (Portrait)', value: '1024x1792' },
					{ name: '1792x1024 (Landscape)', value: '1792x1024' },
					{ name: '1536x1536', value: '1536x1536' },
					{ name: '2048x2048', value: '2048x2048' },
					{ name: '4096x4096 (4K)', value: '4096x4096' },
				],
				default: '1024x1024',
				description: 'Size of the generated image. Available sizes vary by model.',
			},
			{
				displayName: 'Aspect Ratio',
				name: 'aspect_ratio',
				type: 'options',
				options: [
					{ name: 'Auto (Match Input)', value: 'auto' },
					{ name: '1:1 (Square)', value: '1:1' },
					{ name: '3:2', value: '3:2' },
					{ name: '2:3', value: '2:3' },
					{ name: '4:3', value: '4:3' },
					{ name: '3:4', value: '3:4' },
					{ name: '4:5', value: '4:5' },
					{ name: '5:4', value: '5:4' },
					{ name: '16:9', value: '16:9' },
					{ name: '9:16', value: '9:16' },
					{ name: '21:9 (Ultrawide)', value: '21:9' },
				],
				default: 'auto',
				description: 'Aspect ratio for models that support it (e.g., Nano Banana)',
			},
			{
				displayName: 'Quality (GPT Image)',
				name: 'quality',
				type: 'options',
				options: [
					{ name: 'Low', value: 'low' },
					{ name: 'Medium', value: 'medium' },
					{ name: 'High', value: 'high' },
				],
				default: 'medium',
				description: 'Quality level for GPT Image models',
			},
			{
				displayName: 'Number of Images',
				name: 'n',
				type: 'number',
				default: 1,
				description: 'Number of images to generate (max varies by model)',
				typeOptions: { minValue: 1, maxValue: 10 },
			},
			{
				displayName: 'Response Format',
				name: 'response_format',
				type: 'options',
				options: [
					{ name: 'Base64 JSON', value: 'b64_json' },
					{ name: 'URL', value: 'url' },
				],
				default: 'b64_json',
				description: 'Format of the generated image response',
			},
			{
				displayName: 'Output Format',
				name: 'output_format',
				type: 'options',
				options: [
					{ name: 'JPEG', value: 'jpeg' },
					{ name: 'PNG', value: 'png' },
					{ name: 'WebP', value: 'webp' },
				],
				default: 'jpeg',
				description: 'Output image format (for models that support it)',
			},
			{
				displayName: 'Image Data URL (for Img2img)',
				name: 'imageDataUrl',
				type: 'string',
				default: '',
				description: 'Base64 data URL of input image for image-to-image generation',
			},
			{
				displayName: 'Multiple Images (for Img2img)',
				name: 'imageDataUrls',
				type: 'json',
				default: '[]',
				description: 'Array of base64 data URLs for multi-image models (up to 4 for FLUX.2)',
			},
			{
				displayName: 'Mask Data URL (for Inpainting)',
				name: 'maskDataUrl',
				type: 'string',
				default: '',
				description: 'Base64 data URL of mask for inpainting',
			},
			{
				displayName: 'Strength',
				name: 'strength',
				type: 'number',
				default: 0.8,
				description: 'How much to transform the image (0.0-1.0) for img2img',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Guidance Scale / CFG Scale',
				name: 'guidance_scale',
				type: 'number',
				default: 7.5,
				description: 'Prompt adherence level (1-20). Higher = follows prompt more closely.',
				typeOptions: { minValue: 0, maxValue: 35, numberStepSize: 0.5 },
			},
			{
				displayName: 'Inference Steps',
				name: 'num_inference_steps',
				type: 'number',
				default: 30,
				description: 'Number of inference steps (quality vs speed). Model-dependent.',
				typeOptions: { minValue: 1, maxValue: 100 },
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'number',
				default: -1,
				description: 'Random seed for reproducibility (-1 = random)',
			},
			{
				displayName: 'Negative Prompt',
				name: 'negative_prompt',
				type: 'string',
				default: '',
				description: 'What to avoid in the image (supported by SD, Ideogram, etc.)',
			},
			{
				displayName: 'Style (DALL-E 3)',
				name: 'style',
				type: 'options',
				options: [
					{ name: 'Vivid', value: 'vivid' },
					{ name: 'Natural', value: 'natural' },
				],
				default: 'vivid',
				description: 'Choose between vivid (hyper-real/dramatic) or natural',
			},
			{
				displayName: 'Style Type (Ideogram)',
				name: 'style_type',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'Auto' },
					{ name: 'General', value: 'General' },
					{ name: 'Realistic', value: 'Realistic' },
					{ name: 'Design', value: 'Design' },
					{ name: 'Render 3D', value: 'Render 3D' },
					{ name: 'Anime', value: 'Anime' },
				],
				default: 'Auto',
				description: 'Style type for Ideogram models',
			},
			{
				displayName: 'Magic Prompt (Ideogram)',
				name: 'magic_prompt_option',
				type: 'options',
				options: [
					{ name: 'On', value: 'On' },
					{ name: 'Off', value: 'Off' },
				],
				default: 'On',
				description: 'Enable AI prompt enhancement for Ideogram',
			},
			{
				displayName: 'Prompt Expansion',
				name: 'enable_prompt_expansion',
				type: 'boolean',
				default: false,
				description: 'Enable AI-powered prompt enhancement (Hunyuan, etc.)',
			},
			{
				displayName: 'Kontext Max Mode',
				name: 'kontext_max_mode',
				type: 'boolean',
				default: false,
				description: 'Enhanced context mode (flux-kontext only)',
			},
			{
				displayName: 'Enable Safety Checker',
				name: 'enable_safety_checker',
				type: 'boolean',
				default: true,
				description: 'Enable content safety filtering',
			},
			{
				displayName: 'LoRA URL 1',
				name: 'lora_url_1',
				type: 'string',
				default: '',
				description: 'Path to LoRA model (e.g., owner/model-name or .safetensors URL)',
			},
			{
				displayName: 'LoRA Scale 1',
				name: 'lora_scale_1',
				type: 'number',
				default: 1,
				description: 'Strength of LoRA (0.0 to 4.0)',
				typeOptions: { minValue: 0, maxValue: 4, numberStepSize: 0.1 },
			},
		],
	},
];
