/* eslint-disable n8n-nodes-base/node-param-collection-type-unsorted-items, n8n-nodes-base/node-param-options-type-unsorted-items, n8n-nodes-base/node-param-description-boolean-without-whether */
import type { INodeProperties } from 'n8n-workflow';

export const chatNanoGPTParameterProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['chat'],
			},
		},
		options: [
			{
				name: 'Chat Completion',
				value: 'chatCompletion',
				description: 'Generate chat completions (OpenAI-compatible)',
				action: 'Generate chat completion',
			},
			{
				name: 'Create Response',
				value: 'createResponse',
				description: 'Create a response (OpenAI Responses API)',
				action: 'Create response',
			},
			{
				name: 'Get Response',
				value: 'getResponse',
				description: 'Retrieve a stored response by ID',
				action: 'Get response',
			},
			{
				name: 'Delete Response',
				value: 'deleteResponse',
				description: 'Delete a stored response',
				action: 'Delete response',
			},
			{
				name: 'Create Message',
				value: 'createMessage',
				description: 'Create a message (Anthropic-compatible)',
				action: 'Create message',
			},
		],
		default: 'chatCompletion',
	},

	{
		displayName: 'Model',
		name: 'model',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['chat'],
				operation: ['chatCompletion', 'createResponse', 'createMessage'],
			},
		},
		default: 'openai/gpt-4o',
		description: 'Model to use for the request',
	},

	{
		displayName: 'Messages',
		name: 'messages',
		type: 'json',
		displayOptions: {
			show: {
				operation: ['chatCompletion', 'createMessage'],
			},
		},
		default: '[{"role": "user", "content": "Hello"}]',
		description: 'Array of message objects with role and content',
	},

	{
		displayName: 'Response ID',
		name: 'responseId',
		type: 'string',
		displayOptions: {
			show: {
				operation: ['getResponse', 'deleteResponse'],
			},
		},
		default: '',
		required: true,
		description: 'The ID of the response to retrieve or delete',
	},

	{
		displayName: 'Input',
		name: 'responseInput',
		type: 'string',
		displayOptions: {
			show: {
				operation: ['createResponse'],
			},
		},
		default: '',
		required: true,
		description: 'The input text or conversation for the response',
	},

	{
		displayName: 'Instructions',
		name: 'instructions',
		type: 'string',
		displayOptions: {
			show: {
				operation: ['createResponse'],
			},
		},
		default: '',
		description: 'System instructions for the model',
	},

	{
		displayName: 'Advanced Options',
		name: 'responsesAdvancedOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				operation: ['createResponse'],
			},
		},
		options: [
			{
				displayName: 'Max Output Tokens',
				name: 'max_output_tokens',
				type: 'number',
				default: 4096,
				description: 'Maximum tokens in the response (minimum: 16)',
				typeOptions: { minValue: 16 },
			},
			{
				displayName: 'Temperature',
				name: 'temperature',
				type: 'number',
				default: 1,
				description: 'Sampling temperature (0-2). Not supported by reasoning models.',
				typeOptions: { minValue: 0, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Top P',
				name: 'top_p',
				type: 'number',
				default: 1,
				description: 'Nucleus sampling parameter. Not supported by reasoning models.',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Frequency Penalty',
				name: 'frequency_penalty',
				type: 'number',
				default: 0,
				description: 'Frequency penalty for sampling (-2.0 to 2.0)',
				typeOptions: { minValue: -2, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Presence Penalty',
				name: 'presence_penalty',
				type: 'number',
				default: 0,
				description: 'Presence penalty for sampling (-2.0 to 2.0)',
				typeOptions: { minValue: -2, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Top Log Probabilities',
				name: 'top_logprobs',
				type: 'number',
				default: 0,
				description: 'Number of top logprobs to return (0-20)',
				typeOptions: { minValue: 0, maxValue: 20 },
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'number',
				default: 0,
				description: 'Random seed for reproducibility',
			},
			{
				displayName: 'Store',
				name: 'store',
				type: 'boolean',
				default: true,
				description: 'Store response for later retrieval',
			},
			{
				displayName: 'Previous Response ID',
				name: 'previous_response_id',
				type: 'string',
				default: '',
				description: 'Link to previous response for conversation threading',
			},
			{
				displayName: 'Tools',
				name: 'tools',
				type: 'json',
				default: '[]',
				description: 'Array of tools available to the model',
			},
			{
				displayName: 'Tool Choice',
				name: 'tool_choice',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'None', value: 'none' },
					{ name: 'Required', value: 'required' },
				],
				default: 'auto',
				description: 'How the model should use tools',
			},
			{
				displayName: 'Parallel Tool Calls',
				name: 'parallel_tool_calls',
				type: 'boolean',
				default: false,
				description: 'Allow multiple tool calls in parallel',
			},
			{
				displayName: 'Max Tool Calls',
				name: 'max_tool_calls',
				type: 'number',
				default: 0,
				description: 'Maximum number of tool calls allowed (0 = unlimited)',
			},
			{
				displayName: 'Reasoning Effort',
				name: 'reasoning_effort',
				type: 'options',
				options: [
					{ name: 'Low', value: 'low' },
					{ name: 'Medium', value: 'medium' },
					{ name: 'High', value: 'high' },
				],
				default: 'medium',
				description: 'Reasoning effort level for o1/o3 models',
			},
			{
				displayName: 'Reasoning Summary',
				name: 'reasoning_summary',
				type: 'options',
				options: [
					{ name: 'None', value: 'none' },
					{ name: 'Auto', value: 'auto' },
					{ name: 'Detailed', value: 'detailed' },
					{ name: 'Concise', value: 'concise' },
				],
				default: 'auto',
				description: 'Reasoning summary format',
			},
			{
				displayName: 'Text Format',
				name: 'text_format',
				type: 'options',
				options: [
					{ name: 'Text', value: 'text' },
					{ name: 'JSON Object', value: 'json_object' },
					{ name: 'JSON Schema', value: 'json_schema' },
				],
				default: 'text',
				description: 'Response text format',
			},
			{
				displayName: 'JSON Schema',
				name: 'json_schema',
				type: 'json',
				default: '{}',
				description: 'JSON schema for structured output',
			},
			{
				displayName: 'Verbosity',
				name: 'verbosity',
				type: 'options',
				options: [
					{ name: 'Low', value: 'low' },
					{ name: 'Medium', value: 'medium' },
					{ name: 'High', value: 'high' },
				],
				default: 'medium',
				description: 'Response verbosity level',
			},
			{
				displayName: 'Truncation',
				name: 'truncation',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'Disabled', value: 'disabled' },
				],
				default: 'disabled',
				description: 'Truncation strategy',
			},
			{
				displayName: 'Background',
				name: 'background',
				type: 'boolean',
				default: false,
				description: 'Enable background/async processing',
			},
			{
				displayName: 'Service Tier',
				name: 'service_tier',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'Default', value: 'default' },
					{ name: 'Flex', value: 'flex' },
					{ name: 'Priority', value: 'priority' },
				],
				default: 'auto',
				description: 'Service tier for the request',
			},
			{
				displayName: 'User',
				name: 'user',
				type: 'string',
				default: '',
				description: 'Unique user identifier',
			},
			{
				displayName: 'Metadata',
				name: 'metadata',
				type: 'json',
				default: '{}',
				description: 'Custom metadata (max 16 keys)',
			},
		],
	},

	{
		displayName: 'Max Tokens',
		name: 'maxTokens',
		type: 'number',
		displayOptions: {
			show: {
				operation: ['createMessage'],
			},
		},
		default: 4096,
		description: 'Maximum number of tokens to generate',
	},

	{
		displayName: 'System Prompt',
		name: 'systemPrompt',
		type: 'string',
		displayOptions: {
			show: {
				operation: ['createMessage'],
			},
		},
		default: '',
		description: 'System prompt for the conversation',
	},

	{
		displayName: 'Advanced Options',
		name: 'messagesAdvancedOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				operation: ['createMessage'],
			},
		},
		options: [
			{
				displayName: 'Temperature',
				name: 'temperature',
				type: 'number',
				default: 1,
				description: 'Sampling temperature',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.1 },
			},
			{
				displayName: 'Top P',
				name: 'top_p',
				type: 'number',
				default: 1,
				description: 'Nucleus sampling parameter',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Top K',
				name: 'top_k',
				type: 'number',
				default: 0,
				description: 'Top-k sampling parameter',
			},
			{
				displayName: 'Stop Sequences',
				name: 'stop_sequences',
				type: 'string',
				default: '',
				description: 'Comma-separated list of stop sequences',
			},
			{
				displayName: 'Tools',
				name: 'tools',
				type: 'json',
				default: '[]',
				description: 'Tool definitions for function calling',
			},
			{
				displayName: 'Tool Choice',
				name: 'tool_choice',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'None', value: 'none' },
					{ name: 'Any', value: 'any' },
					{ name: 'Required', value: 'required' },
				],
				default: 'auto',
				description: 'Tool choice mode',
			},
			{
				displayName: 'Disable Parallel Tool Use',
				name: 'disable_parallel_tool_use',
				type: 'boolean',
				default: false,
				description: 'Disable parallel tool calls',
			},
			{
				displayName: 'Enable Extended Thinking',
				name: 'thinking_enabled',
				type: 'boolean',
				default: false,
				description: 'Enable extended thinking for supported models',
			},
			{
				displayName: 'Thinking Budget Tokens',
				name: 'thinking_budget_tokens',
				type: 'number',
				default: 8192,
				description: 'Token budget for extended thinking (must be >= 1024)',
				typeOptions: { minValue: 1024 },
			},
			{
				displayName: 'Enable Prompt Caching',
				name: 'prompt_caching',
				type: 'boolean',
				default: false,
				description: 'Enable prompt caching (requires anthropic-beta header)',
			},
		],
	},

	{
		displayName: 'Advanced Options',
		name: 'chatAdvancedOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				operation: ['chatCompletion'],
			},
		},
		options: [
			{
				displayName: 'Temperature',
				name: 'temperature',
				type: 'number',
				default: 0.7,
				description: 'Sampling temperature (0-2). Higher values make output more random. Default: 0.7',
				typeOptions: { minValue: 0, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Max Tokens',
				name: 'max_tokens',
				type: 'number',
				default: 4096,
				description: 'Maximum number of tokens to generate',
			},
			{
				displayName: 'Top P',
				name: 'top_p',
				type: 'number',
				default: 1,
				description: 'Nucleus sampling parameter (0-1)',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Top K',
				name: 'top_k',
				type: 'number',
				default: 0,
				description: 'Top-k sampling parameter. 0 means disabled.',
			},
			{
				displayName: 'Min P',
				name: 'min_p',
				type: 'number',
				default: 0,
				description: 'Minimum probability sampling parameter (0-1)',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Seed',
				name: 'seed',
				type: 'number',
				default: 0,
				description: 'Random seed for reproducibility. 0 means random.',
			},
			{
				displayName: 'Frequency Penalty',
				name: 'frequency_penalty',
				type: 'number',
				default: 0,
				description: 'Penalty for token frequency (-2.0 to 2.0)',
				typeOptions: { minValue: -2, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Presence Penalty',
				name: 'presence_penalty',
				type: 'number',
				default: 0,
				description: 'Penalty for token presence (-2.0 to 2.0)',
				typeOptions: { minValue: -2, maxValue: 2, numberStepSize: 0.1 },
			},
			{
				displayName: 'Repetition Penalty',
				name: 'repetition_penalty',
				type: 'number',
				default: 1,
				description: 'Repetition penalty (1.0 means no penalty)',
			},
			{
				displayName: 'Stop Sequences',
				name: 'stop',
				type: 'string',
				default: '',
				description: 'Comma-separated list of stop sequences',
			},
			{
				displayName: 'Return Log Probabilities',
				name: 'logprobs',
				type: 'boolean',
				default: false,
				description: 'Whether to return log probabilities of tokens',
			},
			{
				displayName: 'Top Log Probabilities',
				name: 'top_logprobs',
				type: 'number',
				default: 0,
				description: 'Number of top logprobs to return (0-20)',
				typeOptions: { minValue: 0, maxValue: 20 },
			},
			{
				displayName: 'Tools',
				name: 'tools',
				type: 'json',
				default: '[]',
				description: 'Array of tool definitions for function calling',
			},
			{
				displayName: 'Tool Choice',
				name: 'tool_choice',
				type: 'options',
				options: [
					{ name: 'Auto', value: 'auto' },
					{ name: 'None', value: 'none' },
					{ name: 'Required', value: 'required' },
				],
				default: 'auto',
				description: 'How to select tools',
			},
			{
				displayName: 'Parallel Tool Calls',
				name: 'parallel_tool_calls',
				type: 'boolean',
				default: true,
				description: 'Allow multiple tool calls in parallel',
			},
			{
				displayName: 'Enable Web Search',
				name: 'linkup_enabled',
				type: 'boolean',
				default: false,
				description: 'Enable real-time web search (Linkup)',
			},
			{
				displayName: 'Web Search Provider',
				name: 'linkup_provider',
				type: 'options',
				options: [
					{ name: 'Linkup', value: 'linkup' },
					{ name: 'Tavily', value: 'tavily' },
					{ name: 'Exa', value: 'exa' },
					{ name: 'Kagi', value: 'kagi' },
				],
				default: 'linkup',
				description: 'Web search provider to use',
			},
			{
				displayName: 'Web Search Depth',
				name: 'linkup_depth',
				type: 'options',
				options: [
					{ name: 'Standard ($0.006)', value: 'standard' },
					{ name: 'Deep ($0.06)', value: 'deep' },
				],
				default: 'standard',
			},
			{
				displayName: 'Search Context Size',
				name: 'linkup_search_context_size',
				type: 'options',
				options: [
					{ name: 'Low', value: 'low' },
					{ name: 'Medium', value: 'medium' },
					{ name: 'High', value: 'high' },
				],
				default: 'medium',
				description: 'Amount of search context to include',
			},
			{
				displayName: 'Search Type',
				name: 'linkup_search_type',
				type: 'options',
				options: [
					{ name: 'Web', value: 'web' },
					{ name: 'News', value: 'news' },
					{ name: 'Search', value: 'search' },
				],
				default: 'web',
				description: 'Type of search (Kagi only)',
			},
			{
				displayName: 'Enable URL Scraping',
				name: 'scraping',
				type: 'boolean',
				default: false,
				description: 'Enable scraping of URLs in the conversation',
			},
			{
				displayName: 'Reasoning Effort',
				name: 'reasoning_effort',
				type: 'options',
				options: [
					{ name: 'Low', value: 'low' },
					{ name: 'Medium', value: 'medium' },
					{ name: 'High', value: 'high' },
				],
				default: 'medium',
				description: 'Reasoning effort level for o1/o3 models',
			},
			{
				displayName: 'Exclude Reasoning',
				name: 'reasoning_exclude',
				type: 'boolean',
				default: false,
				description: 'Exclude reasoning from response',
			},
			{
				displayName: 'Enable Prompt Caching',
				name: 'prompt_caching_enabled',
				type: 'boolean',
				default: false,
				description: 'Enable prompt caching for Claude models',
			},
			{
				displayName: 'Cache TTL',
				name: 'prompt_caching_ttl',
				type: 'options',
				options: [
					{ name: '5 Minutes', value: '5m' },
					{ name: '1 Hour', value: '1h' },
				],
				default: '5m',
				description: 'Cache time-to-live',
			},
			{
				displayName: 'Sticky Provider',
				name: 'prompt_caching_sticky_provider',
				type: 'boolean',
				default: false,
				description: 'Disable failover to preserve cache consistency',
			},
			{
				displayName: 'Enable Memory',
				name: 'memory_enabled',
				type: 'boolean',
				default: false,
				description: 'Enable context memory',
			},
			{
				displayName: 'Memory Expiration Days',
				name: 'memory_expiration_days',
				type: 'number',
				default: 7,
				description: 'Number of days to keep memory',
			},
			{
				displayName: 'Include YouTube Transcripts',
				name: 'youtube_transcripts',
				type: 'boolean',
				default: false,
				description: 'Include YouTube video transcripts in context',
			},
			{
				displayName: 'Response Format',
				name: 'response_format_type',
				type: 'options',
				options: [
					{ name: 'Text', value: 'text' },
					{ name: 'JSON Object', value: 'json_object' },
					{ name: 'JSON Schema', value: 'json_schema' },
				],
				default: 'text',
				description: 'Response format type',
			},
			{
				displayName: 'JSON Schema',
				name: 'json_schema',
				type: 'json',
				default: '{}',
				description: 'JSON schema for structured output (when response format is JSON Schema)',
			},
			{
				displayName: 'Logit Bias',
				name: 'logit_bias',
				type: 'json',
				default: '{}',
				description: 'JSON object mapping token IDs to bias values (-100 to 100)',
			},
			{
				displayName: 'Tail Free Sampling',
				name: 'tfs',
				type: 'number',
				default: 1,
				description: 'Tail free sampling parameter (0-1). 1 means disabled.',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Typical P',
				name: 'typical_p',
				type: 'number',
				default: 1,
				description: 'Typical sampling parameter (0-1). 1 means disabled.',
				typeOptions: { minValue: 0, maxValue: 1, numberStepSize: 0.05 },
			},
			{
				displayName: 'Mirostat Mode',
				name: 'mirostat_mode',
				type: 'options',
				options: [
					{ name: 'Disabled', value: 0 },
					{ name: 'Mirostat 1', value: 1 },
					{ name: 'Mirostat 2', value: 2 },
				],
				default: 0,
				description: 'Mirostat sampling mode',
			},
			{
				displayName: 'Mirostat Tau',
				name: 'mirostat_tau',
				type: 'number',
				default: 5,
				description: 'Mirostat target entropy',
			},
			{
				displayName: 'Mirostat Eta',
				name: 'mirostat_eta',
				type: 'number',
				default: 0.1,
				description: 'Mirostat learning rate',
			},
			{
				displayName: 'Min Tokens',
				name: 'min_tokens',
				type: 'number',
				default: 0,
				description: 'Minimum number of tokens to generate',
			},
		],
	},
];
